import {HeyU, Councel, Merkury} from '../images'

export const portfolioData = [
    {
        name: "Static Landing pages", 
        slug: "static-landing-pages", 
        description: "",
        links: "",
        webLinks: [HeyU, Councel, Merkury],
        techs: ['Html5', 'Css3', 'Jquery', 'Media Query', 'Bootsrap'],
        startDate: "Feb/2020",
        endDate: "Apr/2020",  
        id: 6, 
    },
    {
        name: "Sloon Mobile App",
        slug: "saloon-mobile-app", 
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        links: "",
        techs: ['Node.js', 'React Native Expo', 'javascript', 'Styled-components'],
        startDate: "Jun/2020", 
        endDate: "Oct/2020", 
        id: 1, 
   },
    {
        name: "Emerge Youth Program", 
        slug: "emerge-youth-program", 
        description: "",
        links: "https://eyp.emergeforward.com/",
        techs: ['Node.js', 'React.js', 'javascript', 'Ant Design', 'Styled-components'],
        startDate: "Oct/2020", 
        endDate: "Feb/2021", 
        id: 2, 
    },
    {
        name: "Validator",
        slug: "validator",  
        description: "",
        links: "",
        techs: ['Node.js', 'React.js', 'javascript', 'Ant Design', 'Styled-components'],
        startDate: "Mar/2021", 
        endDate: "Jun/2021", 
        id: 3, 
    },
    {
        name: "Investment Markets", 
        slug: "investmentmarkets", 
        description: "Currently i am working on UI , UX and responsiveness in the investment markets web and i am doing fully responsiveness on every device.",
        links: "https://uat.investmentmarkets.com.au",
        techs: ['Node.js', 'Next.js', 'javascript', 'Bootstrap', 'Styled-components'],
        startDate: "Jul/2021", 
        endDate: "Continued", 
        id: 4, 
    },
    {
        name: "Investment Markets Landing page", 
        slug: "investment-market-landing-page", 
        description: "I create Investment Markets landing page and have three sections header, services and footer, and in the header section have IM logo of company and form for Register you Interest. and i have done that integration rest Api in the register form and this web page is fully mobile responsive.",
        links: "https://investmentmarkets.com.au",
        techs: ['Next.js', 'javascript', 'Bootstrap', 'Styled-components'],
        startDate: "Aug/2021", 
        endDate: "Aug/2021",  
        id: 5, 
    },

    
]